 
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Testimonials from "./components/Testimonials";
import HeroSection from "./components/HeroSection";
import Pricing from "./components/Pricing";
import Workflow from "./components/Workflow";
import FeatureSection from "./components/FeatureSection";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />

        {children}
        <Footer />
        </body>
    </html>
  );
}
